# Generated by Django 5.1.1 on 2024-11-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
