# Generated by Django 5.1.1 on 2024-11-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='published_date',
        ),
        migrations.AddField(
            model_name='car',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
