# Generated by Django 5.1.1 on 2024-11-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_car_published_date_car_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
