# Generated by Django 5.1.1 on 2024-11-28 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='visibility',
            field=models.TextField(choices=[('VI', 'VISIBLE'), ('IN', 'INVISIBLE')], default='IN'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='status',
            field=models.TextField(choices=[('DF', 'DRAFT'), ('PN', 'PENDING'), ('PF', 'PUBLISHED')], default='DF'),
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='car.category'),
        ),
        migrations.AddField(
            model_name='car',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='car.tag'),
        ),
    ]
