# Generated by Django 5.1.1 on 2024-11-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_category_tag_comment_content_comment_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='status',
            field=models.CharField(choices=[('PN', 'PENDING'), ('DF', 'DRAFT'), ('PF', 'PUBLISHED')], max_length=2),
        ),
    ]
