# Generated by Django 5.1.1 on 2024-11-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_representation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='visibility',
            field=models.CharField(choices=[('VI', 'VISIBLE'), ('IN', 'INVISIBLE')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='representation',
            name='status',
            field=models.CharField(choices=[('PF', 'PUBLISHED'), ('PN', 'PENDING'), ('DF', 'DRAFT')], max_length=2),
        ),
    ]
