# Generated by Django 5.1.1 on 2024-12-05 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_remove_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='technical_specifications',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='status',
            field=models.CharField(choices=[('PN', 'PENDING'), ('PF', 'PUBLISHED'), ('DF', 'DRAFT')], max_length=2),
        ),
    ]
