# Generated by Django 5.1.1 on 2024-12-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_technical_specifications_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical_specifications',
            name='title',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
