# Generated by Django 5.1.1 on 2024-12-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_alter_technical_specifications_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sliders')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='representation',
            name='status',
            field=models.CharField(choices=[('DF', 'DRAFT'), ('PN', 'PENDING'), ('PF', 'PUBLISHED')], max_length=2),
        ),
    ]
