# Generated by Django 5.1.1 on 2024-12-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_slider_alter_representation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='status',
            field=models.CharField(choices=[('DF', 'DRAFT'), ('PF', 'PUBLISHED'), ('PN', 'PENDING')], max_length=2),
        ),
    ]
