# Generated by Django 5.1.1 on 2024-12-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_car_file_alter_representation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='main_pic',
        ),
        migrations.AlterField(
            model_name='representation',
            name='status',
            field=models.CharField(choices=[('DF', 'DRAFT'), ('PN', 'PENDING'), ('PF', 'PUBLISHED')], max_length=2),
        ),
    ]
