# Generated by Django 5.1.1 on 2025-01-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_remove_car_main_pic_alter_representation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_admin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
