# Generated by Django 5.1.1 on 2025-01-02 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_comment_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='car',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='status',
            field=models.CharField(choices=[('PN', 'PENDING'), ('DF', 'DRAFT'), ('PF', 'PUBLISHED')], max_length=2),
        ),
    ]
