# Generated by Django 5.1.1 on 2025-01-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_comment_car_alter_representation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='status',
            field=models.CharField(choices=[('PN', 'PENDING'), ('PF', 'PUBLISHED'), ('DF', 'DRAFT')], max_length=2),
        ),
    ]
